### ISSUE TITLE
Error reported after import statement execution (just after installation)

### ISSUE THREAD

**Issue by emanueledirosa** [minimaxir/gpt-2-simple#110]
Python 3.6.6 |Anaconda custom (64-bit)| (default, Jun 28 2018, 11:27:44) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import gpt_2_simple as gpt2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Anaconda\envs\tf-gpu\lib\site-packages\gpt_2_simple\__init__.py", line 1, in <module>
    from .gpt_2 import *
  File "C:\Anaconda\envs\tf-gpu\lib\site-packages\gpt_2_simple\gpt_2.py", line 23, in <module>
    from gpt_2_simple.src import model, sample, encoder, memory_saving_gradients
  File "C:\Anaconda\envs\tf-gpu\lib\site-packages\gpt_2_simple\src\memory_saving_gradients.py", line 13, in <module>
    setattr(tf.compat.v1.GraphKeys, "VARIABLES", "variables")
AttributeError: module 'tensorflow._api.v1.compat' has no attribute 'v1'
>>>

**Comment by minimaxir** [comment]
What is your TensorFlow version? I believe this will occur on older TensorFlows.

**Comment by biranchi2018** [comment]
Try installing Tensorflow 1.14  

$ pip3 install tensorflow==1.14 --user

**Comment by nightvision04** [comment]
@emanueledirosa Are you sure that you installed tensorflow and gpt-2-simple to the same environment you are running python from?

If you are using conda, try this list of steps for a clean installation:

conda create --name gpt2 python=3.5
activate gpt2
python -m pip install tensorflow==1.14 --user
python -m pip install install gpt-2-simple

**Comment by Guillaume-slize** [comment]
Hey,
I'm having the same issue.
I re-installed the env as @nightvision04 advised to no avail.
Any pointers to resolve it?

Mac OS.10.14.4 
Tensorflow=1.14
Python 3.5.4 :: Continuum Analytics, Inc.
anaconda  version 5.3.0
