### ISSUE TITLE
ValueError: Variable model/wpe already exists, disallowed

### ISSUE THREAD

**Issue by woctezuma** [minimaxir/gpt-2-simple#12]
I fine-tuned a model for 1000 iterations, and want to do 1000 more. In such cases, I get an error.

```
sess = gpt2.start_tf_sess()

gpt2.finetune(sess,
              run_name=run_name,
              dataset=file_name,
              steps=1000,
              restore_from='fresh',   # change to 'latest' to resume training
              print_every=10,   # how many steps between printing progress
              sample_every=200,   # how many steps to print a demo sample
              save_every=500   # how many steps between saving checkpoint              
              )
```

Here is the error:

```
ValueError                                Traceback (most recent call last)

<ipython-input-16-3052444268f9> in <module>()
      8               print_every=10,   # how many steps between printing progress
      9               sample_every=200,   # how many steps to print a demo sample
---> 10               save_every=500   # how many steps between saving checkpoint
     11               )

/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py in finetune(sess, dataset, steps, model_name, combine, batch_size, learning_rate, accumulate_gradients, restore_from, run_name, sample_every, sample_length, sample_num, save_every, print_every, max_checkpoints, model_load)
    110 
    111     context = tf.placeholder(tf.int32, [batch_size, None])
--> 112     output = model.model(hparams=hparams, X=context)
    113     loss = tf.reduce_mean(
    114         tf.nn.sparse_softmax_cross_entropy_with_logits(

/usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/model.py in model(hparams, X, past, scope, reuse)
    151 
    152         wpe = tf.get_variable('wpe', [hparams.n_ctx, hparams.n_embd],
--> 153                              initializer=tf.random_normal_initializer(stddev=0.01))
    154         wte = tf.get_variable('wte', [hparams.n_vocab, hparams.n_embd],
    155                              initializer=tf.random_normal_initializer(stddev=0.02))

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(name, shape, dtype, initializer, regularizer, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)
   1477       constraint=constraint,
   1478       synchronization=synchronization,
-> 1479       aggregation=aggregation)
   1480 
   1481 

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, var_store, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)
   1218           constraint=constraint,
   1219           synchronization=synchronization,
-> 1220           aggregation=aggregation)
   1221 
   1222   def _get_partitioned_variable(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in get_variable(self, name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, custom_getter, constraint, synchronization, aggregation)
    545           constraint=constraint,
    546           synchronization=synchronization,
--> 547           aggregation=aggregation)
    548 
    549   def _get_partitioned_variable(self,

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _true_getter(name, shape, dtype, initializer, regularizer, reuse, trainable, collections, caching_device, partitioner, validate_shape, use_resource, constraint, synchronization, aggregation)
    497           constraint=constraint,
    498           synchronization=synchronization,
--> 499           aggregation=aggregation)
    500 
    501     # Set trainable value based on synchronization value.

/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    846         tb = [x for x in tb if "tensorflow/python" not in x[0]][:3]
    847         raise ValueError("%s Originally defined at:\n\n%s" % (err_msg, "".join(
--> 848             traceback.format_list(tb))))
    849       found_var = self._vars[name]
    850       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable model/wpe already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/model.py", line 153, in model
    initializer=tf.random_normal_initializer(stddev=0.01))
  File "/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py", line 112, in finetune
    output = model.model(hparams=hparams, X=context)
  File "<ipython-input-7-3052444268f9>", line 10, in <module>
    save_every=500   # how many steps between saving checkpoint

```

**Comment by woctezuma** [comment]
Restarting the VM seems to solve the issue.

**Comment by woctezuma** [comment]
Was my mistake to call the following? Should it have been in its own cell?

```python
sess = gpt2.start_tf_sess()
```
