### ISSUE TITLE
Pipenv and gpt2_download

### ISSUE THREAD

**Issue by ercprk** [minimaxir/gpt-2-simple#181]
I am currently running the example script on the usage part of the README, and getting this error:

`Downloading 124M model...
Traceback (most recent call last):
  File "gpt_2_simple.py", line 3, in <module>
    import gpt_2_simple as gpt2
  File "/Users/Eric/Desktop/SMB-Email-Aid/gpt_2_simple/gpt_2_simple.py", line 24, in <module>
    gpt_2_simple_train("marketing_phrases.txt")
  File "/Users/Eric/Desktop/SMB-Email-Aid/gpt_2_simple/gpt_2_simple.py", line 14, in gpt_2_simple_train
    gpt2.download_gpt2(model_name=model_name)
AttributeError: module 'gpt_2_simple' has no attribute 'download_gpt2'`

I'm running this on a Pipenv shell. How do I get around this?

**Comment by ercprk** [comment]
Nevermind. Stupid mistake: I set the script name also as gpt_2_simple
