### ISSUE TITLE
Newbie issue

### ISSUE THREAD

**Issue by Sadrahel** [minimaxir/gpt-2-simple#297]
Hi thank you very much for your work.

I'd like to fine tune GPT-2.
I installed gpt-2 simple 
then
I just paste your code in jupyter

but the execution give me :

Loading checkpoint models/124M/model.ckpt
INFO:tensorflow:Restoring parameters from models/124M/model.ckpt
Loading dataset...
100%|██████████| 1/1 [00:00<00:00,  1.36it/s]
dataset has 338025 tokens
Training...
---------------------------------------------------------------------------
ResourceExhaustedError                    Traceback (most recent call last)
~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1376     try:
-> 1377       return fn(*args)
   1378     except errors.OpError as e:

~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in _run_fn(feed_dict, fetch_list, target_list, options, run_metadata)
   1359       self._extend_graph()
-> 1360       return self._call_tf_sessionrun(options, feed_dict, fetch_list,
   1361                                       target_list, run_metadata)

~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in _call_tf_sessionrun(self, options, feed_dict, fetch_list, target_list, run_metadata)
   1452                           run_metadata):
-> 1453     return tf_session.TF_SessionRun_wrapper(self._session, options, feed_dict,
   1454                                             fetch_list, target_list,

ResourceExhaustedError: OOM when allocating tensor with shape[1,12,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/h11/attn/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

During handling of the above exception, another exception occurred:

ResourceExhaustedError                    Traceback (most recent call last)
<ipython-input-1-8bf1c987c4e5> in <module>
     19 
     20 sess = gpt2.start_tf_sess()
---> 21 gpt2.finetune(sess,
     22               file_name,
     23               model_name=model_name,

~/.local/lib/python3.8/site-packages/gpt_2_simple/gpt_2.py in finetune(sess, dataset, steps, model_name, model_dir, combine, batch_size, learning_rate, accumulate_gradients, restore_from, run_name, checkpoint_dir, sample_every, sample_length, sample_num, multi_gpu, save_every, print_every, max_checkpoints, use_memory_saving_gradients, only_train_transformer_layers, optimizer, overwrite, reuse)
    337                 sess.run(opt_reset)
    338                 for _ in range(accumulate_gradients):
--> 339                     sess.run(
    340                         opt_compute, feed_dict={context: sample_batch()})
    341                 (v_loss, v_summary) = sess.run((opt_apply, summary_loss))

~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in run(self, fetches, feed_dict, options, run_metadata)
    965 
    966     try:
--> 967       result = self._run(None, fetches, feed_dict, options_ptr,
    968                          run_metadata_ptr)
    969       if run_metadata:

~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in _run(self, handle, fetches, feed_dict, options, run_metadata)
   1188     # or if the call is a partial run that specifies feeds.
   1189     if final_fetches or final_targets or (handle and feed_dict_tensor):
-> 1190       results = self._do_run(handle, final_targets, final_fetches,
   1191                              feed_dict_tensor, options, run_metadata)
   1192     else:

~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in _do_run(self, handle, target_list, fetch_list, feed_dict, options, run_metadata)
   1368 
   1369     if handle is None:
-> 1370       return self._do_call(_run_fn, feeds, fetches, targets, options,
   1371                            run_metadata)
   1372     else:

~/.local/lib/python3.8/site-packages/tensorflow/python/client/session.py in _do_call(self, fn, *args)
   1394                     '\nsession_config.graph_options.rewrite_options.'
   1395                     'disable_meta_optimizer = True')
-> 1396       raise type(e)(node_def, op, message)  # pylint: disable=no-value-for-parameter
   1397 
   1398   def _extend_graph(self):

ResourceExhaustedError: Graph execution error:

Detected at node 'model/h11/attn/MatMul' defined at (most recent call last):
    File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
      return _run_code(code, main_globals, None,
    File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
      exec(code, run_globals)
    File "/usr/lib/python3/dist-packages/ipykernel_launcher.py", line 16, in <module>
      app.launch_new_instance()
    File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 664, in launch_instance
      app.start()
    File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 583, in start
      self.io_loop.start()
    File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 132, in start
      self.asyncio_loop.run_forever()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
      self._run_once()
    File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
      handle._run()
    File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
      self._context.run(self._callback, *self._args)
    File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 758, in _run_callback
      ret = callback()
    File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
      return fn(*args, **kwargs)
    File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1248, in inner
      self.run()
    File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1162, in run
      yielded = self.gen.send(value)
    File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
      yield gen.maybe_future(dispatch(*args))
    File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
      yield gen.maybe_future(handler(stream, idents, msg))
    File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 543, in execute_request
      self.do_execute(
    File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
      yielded = next(result)
    File "/usr/lib/python3/dist-packages/ipykernel/ipkernel.py", line 300, in do_execute
      res = shell.run_cell(code, store_history=store_history, silent=silent)
    File "/usr/lib/python3/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
      return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
    File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2857, in run_cell
      result = self._run_cell(
    File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
      return runner(coro)
    File "/usr/lib/python3/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
      coro.send(None)
    File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3062, in run_cell_async
      has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
    File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
      if (await self.run_code(code, result,  async_=asy)):
    File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
      exec(code_obj, self.user_global_ns, self.user_ns)
    File "<ipython-input-1-8bf1c987c4e5>", line 21, in <module>
      gpt2.finetune(sess,
    File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/gpt_2.py", line 198, in finetune
      output = model.model(hparams=hparams, X=context, gpus=gpus, reuse=reuse)
    File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 203, in model
      h, present = block(h, 'h%d' % layer, past=past, hparams=hparams)
    File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 156, in block
      a, present = attn(norm(x, 'ln_1'), 'attn', nx, past=past, hparams=hparams)
    File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 139, in attn
      a = multihead_attn(q, k, v)
    File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 123, in multihead_attn
      w = tf.matmul(q, k, transpose_b=True)
Node: 'model/h11/attn/MatMul'
OOM when allocating tensor with shape[1,12,1024,1024] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
	 [[{{node model/h11/attn/MatMul}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info. This isn't available when running in Eager mode.

Original stack trace for 'model/h11/attn/MatMul':
  File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3/dist-packages/ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "/usr/lib/python3/dist-packages/traitlets/config/application.py", line 664, in launch_instance
    app.start()
  File "/usr/lib/python3/dist-packages/ipykernel/kernelapp.py", line 583, in start
    self.io_loop.start()
  File "/usr/lib/python3/dist-packages/tornado/platform/asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 570, in run_forever
    self._run_once()
  File "/usr/lib/python3.8/asyncio/base_events.py", line 1859, in _run_once
    handle._run()
  File "/usr/lib/python3.8/asyncio/events.py", line 81, in _run
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/tornado/ioloop.py", line 758, in _run_callback
    ret = callback()
  File "/usr/lib/python3/dist-packages/tornado/stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1248, in inner
    self.run()
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 1162, in run
    yielded = self.gen.send(value)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 365, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/ipykernel/kernelbase.py", line 543, in execute_request
    self.do_execute(
  File "/usr/lib/python3/dist-packages/tornado/gen.py", line 326, in wrapper
    yielded = next(result)
  File "/usr/lib/python3/dist-packages/ipykernel/ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "/usr/lib/python3/dist-packages/ipykernel/zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2857, in run_cell
    result = self._run_cell(
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "/usr/lib/python3/dist-packages/IPython/core/async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3062, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "/usr/lib/python3/dist-packages/IPython/core/interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-1-8bf1c987c4e5>", line 21, in <module>
    gpt2.finetune(sess,
  File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/gpt_2.py", line 198, in finetune
    output = model.model(hparams=hparams, X=context, gpus=gpus, reuse=reuse)
  File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 203, in model
    h, present = block(h, 'h%d' % layer, past=past, hparams=hparams)
  File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 156, in block
    a, present = attn(norm(x, 'ln_1'), 'attn', nx, past=past, hparams=hparams)
  File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 139, in attn
    a = multihead_attn(q, k, v)
  File "/home/guillaume/.local/lib/python3.8/site-packages/gpt_2_simple/src/model.py", line 123, in multihead_attn
    w = tf.matmul(q, k, transpose_b=True)
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/util/traceback_utils.py", line 150, in error_handler
    return fn(*args, **kwargs)
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/util/dispatch.py", line 1082, in op_dispatch_handler
    return dispatch_target(*args, **kwargs)
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/ops/math_ops.py", line 3666, in matmul
    return gen_math_ops.batch_mat_mul_v2(
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/ops/gen_math_ops.py", line 1590, in batch_mat_mul_v2
    _, _, _op, _outputs = _op_def_library._apply_op_helper(
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/framework/op_def_library.py", line 740, in _apply_op_helper
    op = g._create_op_internal(op_type_name, inputs, dtypes=None,
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 3776, in _create_op_internal
    ret = Operation(
  File "/home/guillaume/.local/lib/python3.8/site-packages/tensorflow/python/framework/ops.py", line 2175, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)

**Comment by Sadrahel** [comment]
Can anyone give me some advises ?

**Comment by mrx23dot** [comment]
I have the same issue after running example on win10.
I have no GPUs.

```
Original stack trace for 'save/RestoreV2':
  File "<stdin>", line 4, in <module>
  File "C:\Python37\lib\site-packages\gpt_2_simple\gpt_2.py", line 245, in finetune
    max_to_keep=max_checkpoints)
  File "C:\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 933, in __init__
    self.build()
  File "C:\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 945, in build
    self._build(self._filename, build_save=True, build_restore=True)
  File "C:\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 983, in _build
    build_restore=build_restore)
  File "C:\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 544, in _build_internal
    restore_sequentially, reshape)
  File "C:\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 364, in _AddRestoreOps
    restore_sequentially)
  File "C:\Python37\lib\site-packages\tensorflow\python\training\saver.py", line 611, in bulk_restore
    return io_ops.restore_v2(filename_tensor, names, slices, dtypes)
  File "C:\Python37\lib\site-packages\tensorflow\python\ops\gen_io_ops.py", line 1503, in restore_v2
    name=name)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\op_def_library.py", line 799, in _apply_op_helper
    attrs=attr_protos, op_def=op_def)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 3762, in _create_op_internal
    op_def=op_def)
  File "C:\Python37\lib\site-packages\tensorflow\python\framework\ops.py", line 2133, in __init__
    self._traceback = tf_stack.extract_stack_for_node(self._c_op)
```

**Comment by Noorquacker** [comment]
Hi,
First, when you paste code or logs, paste code blocks so that it's easier to read.
Second, look at the line `ResourceExhaustedError: OOM when allocating tensor`. You're running out of VRAM or RAM. Consider using 124M on Google Colab or running it CPU-only on a system with lots of RAM, there are tutorials online for running gpt-2-simple on Colab
