### ISSUE TITLE
doesnt work

### ISSUE THREAD

**Issue by flzpfnove** [minimaxir/gpt-2-simple#313]
Whenever i try to run my code I get this:
Don't tell me to just name the trained thing "run1" because i don't want to, also if there's an option for saving with a custom name there should also be an option for opening with a custom name

`Traceback (most recent call last):
  File "run_gpt2.py", line 20, in <module>
    gpt2.generate(sess, length=lenght, temperature=0.7, prefix=prompt, nsamples=5, batch_size=5)
  File "D:\GPT-2\Python3.7.8\lib\site-packages\gpt_2_simple\gpt_2.py", line 450, in generate
    enc = encoder.get_encoder(checkpoint_path)
  File "D:\GPT-2\Python3.7.8\lib\site-packages\gpt_2_simple\src\encoder.py", line 109, in get_encoder
    with open(os.path.join(checkpoint_path, 'encoder.json'), 'r') as f:
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint\\run1\\encoder.json'`

**Comment by flzpfnove** [comment]
so appearently you need to have a run named "run1" if you want to have any others? well i guess ill just keep it
