### ISSUE TITLE
There was an error occurred when generating.

### ISSUE THREAD

**Issue by dickkky** [minimaxir/gpt-2-simple#57]
There was an error, “ValueError: Can't load save_path when it is None.”, occurred when using “gpt_2_simple generate” after finetuned. How to solve it?

**Comment by minimaxir** [comment]
Can you give a more detailed error stack trace?

This shouldn't be happening with a straight `gpt_2_simple generate`. Are you running the script where the folder `checkpoint/run1` is present?

**Comment by dickkky** [comment]
You mean that  the  script must be run at the folder checkpoint/run1?

**Comment by minimaxir** [comment]
In the parent directory of that folder, yes.

**Comment by dickkky** [comment]
the error was still:
Traceback (most recent call last):
  File "D:\Users\admin\AppData\Local\Programs\Python\Python36\Scripts\gpt_2_simple-script.py", line 11, in <module>
    load_entry_point('gpt-2-simple==0.4.2', 'console_scripts', 'gpt_2_simple')()
  File "D:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\gpt_2_simple-0.4.2-py3.6.egg\gpt_2_simple\gpt_2.py", line 595, in cmd
  File "D:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\gpt_2_simple-0.4.2-py3.6.egg\gpt_2_simple\gpt_2.py", line 624, in cmd_generate
  File "D:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\gpt_2_simple-0.4.2-py3.6.egg\gpt_2_simple\gpt_2.py", line 304, in load_gpt2
  File "D:\Users\admin\AppData\Local\Programs\Python\Python36\lib\site-packages\tensorflow\python\training\saver.py", line 1264, in restore
    raise ValueError("Can't load save_path when it is None.")
ValueError: Can't load save_path when it is None.

**Comment by dickkky** [comment]
What files should be include in folder run1?

**Comment by osirisguitar** [comment]
I got this error when finetuning failed. There were some files in checkpoint/run1, but not the model. There should be three files called model-<epochs>.something in run1.

**Comment by joelprince25** [comment]
I'm running into this same error when I try to re-train from a checkpoint.

`tf.reset_default_graph()
sess = gpt2.start_tf_sess()
#gpt2.load_gpt2(sess, run_name='run1top20agents11000')
gpt2.finetune(sess,
              dataset=file_name,
              model_name='355M',
              steps=10000,
              restore_from='lastest',
              checkpoint_dir = 'checkpoint',
              run_name='run1',
              print_every=10,
              sample_every=500,
              save_every=500,
              learning_rate = 0.0001,
              multi_gpu = False
              )`

I am running this in the parent directory and checkpoint/run1 has the three model files.

**Comment by joelprince25** [comment]
I'm running into this same error when I try to re-train from a checkpoint.

```tf.reset_default_graph()
sess = gpt2.start_tf_sess()
gpt2.finetune(sess,
              dataset=file_name,
              model_name='355M',
              steps=10000,
              restore_from='lastest',
              checkpoint_dir = 'checkpoint',
              run_name='run1',
              print_every=10,
              sample_every=500,
              save_every=500,
              learning_rate = 0.0001,
              multi_gpu = False
              )
```
I am running this in the parent directory and checkpoint/run1 has the three model files.

**Here's the error:**

Loading checkpoint None

ValueError                                Traceback (most recent call last)
<ipython-input-12-4af668a4199a> in <module>()
     13               save_every=500,
     14               learning_rate = 0.0001,
---> 15               multi_gpu = False
     16               )

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/gpt_2_simple/gpt_2.py in finetune(sess, dataset, steps, model_name, model_dir, combine, batch_size, learning_rate, accumulate_gradients, restore_from, run_name, checkpoint_dir, sample_every, sample_length, sample_num, multi_gpu, save_every, print_every, max_checkpoints, use_memory_saving_gradients, only_train_transformer_layers, optimizer, overwrite)
    255         ckpt = tf.train.latest_checkpoint(restore_from)
    256     print('Loading checkpoint', ckpt)
--> 257     saver.restore(sess, ckpt)
    258 
    259     print('Loading dataset...')

~/anaconda3/envs/tensorflow_p36/lib/python3.6/site-packages/tensorflow_core/python/training/saver.py in restore(self, sess, save_path)
   1281       return
   1282     if save_path is None:
-> 1283       raise ValueError("Can't load save_path when it is None.")
   1284 
   1285     checkpoint_prefix = compat.as_text(save_path)

ValueError: Can't load save_path when it is None.
