### ISSUE TITLE
[Errno 2] No such file or directory: 'checkpoint/run1/hparams.json'

### ISSUE THREAD

**Issue by Johk3** [minimaxir/gpt-2-simple#59]
2019-05-20 17:43:33.108064: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 AVX512F FMA
2019-05-20 17:43:33.111857: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 2693670000 Hz
2019-05-20 17:43:33.112071: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x5589988bd010 executing computations on platform Host. Devices:
2019-05-20 17:43:33.112093: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Traceback (most recent call last):
  File "/root/anaconda3/envs/finance/bin/gpt_2_simple", line 11, in <module>
    load_entry_point('gpt-2-simple==0.5', 'console_scripts', 'gpt_2_simple')()
  File "/root/anaconda3/envs/finance/lib/python3.6/site-packages/gpt_2_simple-0.5-py3.6.egg/gpt_2_simple/gpt_2.py", line 660, in cmd
  File "/root/anaconda3/envs/finance/lib/python3.6/site-packages/gpt_2_simple-0.5-py3.6.egg/gpt_2_simple/gpt_2.py", line 691, in cmd_generate
  File "/root/anaconda3/envs/finance/lib/python3.6/site-packages/gpt_2_simple-0.5-py3.6.egg/gpt_2_simple/gpt_2.py", line 302, in load_gpt2
FileNotFoundError: [Errno 2] No such file or directory: 'checkpoint/run1/hparams.json'

**Comment by minimaxir** [comment]
Did you finetune a model first?

**Comment by woctezuma** [comment]
#10

**Comment by Johk3** [comment]
Got it, it was the finetuning
