### ISSUE TITLE
Issue with training from a CSV IndexError: list index out of range

### ISSUE THREAD

**Issue by matthewford** [minimaxir/gpt-2-simple#77]
Hi, 
I'm having a slight issue training a CSV file, I get:
```
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-6-5ba6fdb2b35e> in <module>()
     10               print_every=10,
     11               sample_every=100,
---> 12               save_every=50,
     13               )

6 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/variable_scope.py in _get_single_variable(self, name, shape, dtype, initializer, regularizer, partition_info, reuse, trainable, collections, caching_device, validate_shape, use_resource, constraint, synchronization, aggregation)
    862         tb = [x for x in tb if "tensorflow/python" not in x[0]][:5]
    863         raise ValueError("%s Originally defined at:\n\n%s" %
--> 864                          (err_msg, "".join(traceback.format_list(tb))))
    865       found_var = self._vars[name]
    866       if not shape.is_compatible_with(found_var.get_shape()):

ValueError: Variable model/wpe already exists, disallowed. Did you mean to set reuse=True or reuse=tf.AUTO_REUSE in VarScope? Originally defined at:

  File "/usr/local/lib/python3.6/dist-packages/gpt_2_simple/src/model.py", line 153, in model
    initializer=tf.random_normal_initializer(stddev=0.01))
  File "/usr/local/lib/python3.6/dist-packages/gpt_2_simple/gpt_2.py", line 165, in finetune
    output = model.model(hparams=hparams, X=context)
  File "<ipython-input-5-c87932f8e741>", line 13, in <module>
    overwrite=True
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2882, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py", line 2828, in run_ast_nodes
    if self.run_code(code, result):
```

File i'm using attached:
[names.csv.zip](https://github.com/minimaxir/gpt-2-simple/files/3341268/names.csv.zip)

**Comment by woctezuma** [comment]
The error message is not the one mentioned in the issue title:

> ValueError: Variable model/wpe already exists, disallowed.

I would try:
1) to restart to Google Colab session,
2) to use a different `run_name`.

**Comment by matthewford** [comment]
Thanks
